### PR TITLE
Release version 1.2.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release version 1.2.2
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @Hlavtox

It seems there's some failed checks :disappointed: 
Could you please check it :pray: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Tests OK after about 100 tries, you can test it :D

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

I can't upgrade the module properly on 8.0.1 :

https://user-images.githubusercontent.com/16019289/212953890-13acc39a-1872-4cdf-a4b0-80d84e583609.mov

Tested on 1.7.8.8 and on branch develop, it is OK.

Could you check ? ^^

**Comment by kpodemski** [comment]
QA: you can use 8.0.2 and latest version of ps_distributionapi client.

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR 🙏 
Tested on:

- 1.7.8.8 : ✔️ 
- 8.0.1 : ✔️ 

LGTM, QA ✅ 

Thanks!

**Comment by Hlavtox** [comment]
Thank you @hibatallahAouadni!

**Pull request merged**
