### PR TITLE
Update short description and logo 

### PR DESCRIPTION
**Pull request by Julievrz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update short description and logo.
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/15858
| How to test?  | Please check that short description and logo are updated.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Ci is broken because of Composer v2.

**Review by sowbiba — APPROVED** [review]

**Comment by Progi1984** [comment]
@Julievrz Could you fix the PR on the good file, please ?

**Comment by Julievrz** [comment]
@Progi1984 What do you mean? 🤔 What is the problem exactly?

**Comment by Progi1984** [comment]
@Julievrz The develop branch has changed. And you must update your branch for fixing the conflicting file.

**Comment by Julievrz** [comment]
I created a new PR

**Pull request closed without merging**
