### PR TITLE
Remove mobile enable/disable

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Removes code related to mobile enable/disable functionality, which has been removed from the core.
| Type?         | refacto
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by boherm — APPROVED** [review]
LGTM, thanks @Hlavtox ;)

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
Thanks @Hlavtox 😄

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Tested on PS 1.7.8.10.

The option to disable/enable on mobile is still present.

Screenshot 2023-10-19 at 14 17 39

I have cleared my PS and browser cache.
The PR is well installed :
Screenshot 2023-10-19 at 14 20 27

Could you check ?

**Comment by Hlavtox** [comment]
@florine2623 That's not the point of this PR. :-) I removed the functionality from inside the module. You need to check the configuration page in `BO > Themes and logo`, there you will see that the options to disable and enable module on mobile was removed.

**Review by kpodemski — CHANGES_REQUESTED** [review]
Correct me if I'm wrong @Hlavtox , but IMO this requires bumping the version of the module and minimum compatibility to v9.

**Comment by Hlavtox** [comment]
@kpodemski We can do it after it's merged, but it will work even for older versions. Just the option to disable/enable modules in the interface of this module will be missing.

**Pull request closed without merging**
